class ROUTES:
    HEALTHCHECK_ROUTE = "/ping"
    DREAM_ROUTE = "/dream"


class BOOLEAN_VALUES:
    TRUE = "true"
    FALSE = "false"


class PROMPT_TYPE:
    SYSTEM_PROMPT = "SYSTEM_PROMPT"
    USER_PROMPT = "USER_PROMPT"


class PROMPT_CATEGORY:
    ROUTINE_GENERATOR = "ROUTINE_GENERATOR"
    DAILY_HABIT_GENERATOR = "DAILY_HABIT_GENERATOR"
    FEAR_AND_MOTIVATION_GENERATOR = "FEAR_AND_MOTIVATION_GENERATOR"


class PATH:
    PROJECT_ROOT = ""


class INTERACTION:
    RESPONSE = "RESPONSE"
    REQUEST = "REQUEST"


class LIFECYCLE_STATE:
    INITIAL = "initial"
    FINAL = "final"
    ACTIVE_CLIENT = "active_client"


class PAYLOAD_CATEGORY:
    USER_FORM_DATA = "USER_FORM_DATA"
    ROUTINE_GENERATOR_DATA = "ROUTINE_GENERATOR_DATA"
    DAILY_HABIT_GENERATOR_DATA = "DAILY_HABIT_GENERATOR_DATA"
    FEAR_AND_MOTIVATION_GENERATOR_DATA = "FEAR_AND_MOTIVATION_GENERATOR_DATA"
