from app.utils.constants import PAYLOAD_CATEGORY

SCHEMA_MAP = {
    PAYLOAD_CATEGORY.USER_FORM_DATA: {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "Life Questions Schema",
        "type": "object",
        "properties": {
            # Career Questions
            "career_fulfilling_career": {"type": "string"},
            "career_definition_of_success": {"type": "string"},
            "career_money_no_object": {"type": "string"},
            "career_irreplaceable_skills": {"type": "string"},
            "career_role_models": {"type": "string"},
            "career_work_environment": {"type": "string"},
            "career_work_team_individually": {"type": "string"},
            "career_ideal_work_life_balance": {"type": "string"},
            "career_work_from_anywhere": {"type": "string"},
            "career_impactful_project": {"type": "string"},
            # Finance Questions
            "finance_financial_freedom": {"type": "string"},
            "finance_passive_income_needed": {"type": "string"},
            "finance_relationship_with_money": {"type": "string"},
            "finance_one_important_financial_decision": {"type": "string"},
            "finance_managing_spending": {"type": "string"},
            "finance_short_term_financial_goals": {"type": "string"},
            "finance_investment_choice": {"type": "string"},
            "finance_dream_budget": {"type": "string"},
            "finance_tracking_finances": {"type": "string"},
            "finance_impact_of_financial_freedom": {"type": "string"},
            # Relationships Questions
            "relationships_qualities_in_relationships": {"type": "string"},
            "relationships_prioritizing_relationships": {"type": "string"},
            "relationships_balancing_career_and_relationships": {"type": "string"},
            "relationships_ideal_partner_dynamic": {"type": "string"},
            "relationships_conflict_resolution": {"type": "string"},
            "relationships_legacy_in_relationships": {"type": "string"},
            "relationships_role_of_friendships": {"type": "string"},
            "relationships_contributing_to_others": {"type": "string"},
            "relationships_boundaries_for_healthy_relationships": {"type": "string"},
            "relationships_ideal_circle_of_people": {"type": "string"},
        },
        "required": [
            "career_fulfilling_career",
            "career_definition_of_success",
            "career_money_no_object",
            "career_irreplaceable_skills",
            "career_role_models",
            "career_work_environment",
            "career_work_team_individually",
            "career_ideal_work_life_balance",
            "career_work_from_anywhere",
            "career_impactful_project",
            "finance_financial_freedom",
            "finance_passive_income_needed",
            "finance_relationship_with_money",
            "finance_one_important_financial_decision",
            "finance_managing_spending",
            "finance_short_term_financial_goals",
            "finance_investment_choice",
            "finance_dream_budget",
            "finance_tracking_finances",
            "finance_impact_of_financial_freedom",
            "relationships_qualities_in_relationships",
            "relationships_prioritizing_relationships",
            "relationships_balancing_career_and_relationships",
            "relationships_ideal_partner_dynamic",
            "relationships_conflict_resolution",
            "relationships_legacy_in_relationships",
            "relationships_role_of_friendships",
            "relationships_contributing_to_others",
            "relationships_boundaries_for_healthy_relationships",
            "relationships_ideal_circle_of_people",
        ],
        "additionalProperties": False,
    },
    PAYLOAD_CATEGORY.ROUTINE_GENERATOR_DATA: {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "Life Systems Schema",
        "type": "object",
        "properties": {
            "career": {
                "type": "object",
                "properties": {
                    "daily_steps": {
                        "type": "object",
                        "properties": {
                            "morning_routine": {"type": "string"},
                            "deep_work": {"type": "string"},
                            "team_engagement": {"type": "string"},
                            "self_reflection": {"type": "string"},
                        },
                        "required": [
                            "morning_routine",
                            "deep_work",
                            "team_engagement",
                            "self_reflection",
                        ],
                        "additionalProperties": False,
                    },
                    "weekly_steps": {
                        "type": "object",
                        "properties": {
                            "strategy_review": {"type": "string"},
                            "team_development": {"type": "string"},
                            "networking": {"type": "string"},
                            "growth_focused_learning": {"type": "string"},
                        },
                        "required": [
                            "strategy_review",
                            "team_development",
                            "networking",
                            "growth_focused_learning",
                        ],
                        "additionalProperties": False,
                    },
                    "monthly_steps": {
                        "type": "object",
                        "properties": {
                            "visionary_planning": {"type": "string"},
                            "high_impact_project": {"type": "string"},
                            "industry_engagement": {"type": "string"},
                            "mentorship": {"type": "string"},
                        },
                        "required": [
                            "visionary_planning",
                            "high_impact_project",
                            "industry_engagement",
                            "mentorship",
                        ],
                        "additionalProperties": False,
                    },
                },
                "required": ["daily_steps", "weekly_steps", "monthly_steps"],
                "additionalProperties": False,
            },
            "finance": {
                "type": "object",
                "properties": {
                    "daily_steps": {
                        "type": "object",
                        "properties": {
                            "financial_review": {"type": "string"},
                            "investment_research": {"type": "string"},
                            "wealth_mindset_practice": {"type": "string"},
                        },
                        "required": [
                            "financial_review",
                            "investment_research",
                            "wealth_mindset_practice",
                        ],
                        "additionalProperties": False,
                    },
                    "weekly_steps": {
                        "type": "object",
                        "properties": {
                            "portfolio_review": {"type": "string"},
                            "smart_spending": {"type": "string"},
                            "growth_oriented_networking": {"type": "string"},
                            "financial_education": {"type": "string"},
                        },
                        "required": [
                            "portfolio_review",
                            "smart_spending",
                            "growth_oriented_networking",
                            "financial_education",
                        ],
                        "additionalProperties": False,
                    },
                    "monthly_steps": {
                        "type": "object",
                        "properties": {
                            "investment_strategy_update": {"type": "string"},
                            "set_financial_milestones": {"type": "string"},
                            "philanthropy_focus": {"type": "string"},
                            "long_term_financial_vision": {"type": "string"},
                        },
                        "required": [
                            "investment_strategy_update",
                            "set_financial_milestones",
                            "philanthropy_focus",
                            "long_term_financial_vision",
                        ],
                        "additionalProperties": False,
                    },
                },
                "required": ["daily_steps", "weekly_steps", "monthly_steps"],
                "additionalProperties": False,
            },
            "relationships": {
                "type": "object",
                "properties": {
                    "daily_steps": {
                        "type": "object",
                        "properties": {
                            "connection_time": {"type": "string"},
                            "self_reflection_on_relationships": {"type": "string"},
                            "communication_practice": {"type": "string"},
                        },
                        "required": [
                            "connection_time",
                            "self_reflection_on_relationships",
                            "communication_practice",
                        ],
                        "additionalProperties": False,
                    },
                    "weekly_steps": {
                        "type": "object",
                        "properties": {
                            "intentional_date_quality_time": {"type": "string"},
                            "social_connections": {"type": "string"},
                            "personal_growth_together": {"type": "string"},
                            "team_bonding": {"type": "string"},
                        },
                        "required": [
                            "intentional_date_quality_time",
                            "social_connections",
                            "personal_growth_together",
                            "team_bonding",
                        ],
                        "additionalProperties": False,
                    },
                    "monthly_steps": {
                        "type": "object",
                        "properties": {
                            "mentorship_support": {"type": "string"},
                            "family_partner_retreats": {"type": "string"},
                            "reflect_on_boundaries": {"type": "string"},
                            "celebrate_milestones": {"type": "string"},
                        },
                        "required": [
                            "mentorship_support",
                            "family_partner_retreats",
                            "reflect_on_boundaries",
                            "celebrate_milestones",
                        ],
                        "additionalProperties": False,
                    },
                },
                "required": ["daily_steps", "weekly_steps", "monthly_steps"],
                "additionalProperties": False,
            },
            "daily_routine": {
                "type": "object",
                "properties": {
                    "morning_routine": {
                        "type": "object",
                        "properties": {
                            "exercise": {"type": "string"},
                            "mindfulness": {"type": "string"},
                            "strategic_planning": {"type": "string"},
                        },
                        "required": ["exercise", "mindfulness", "strategic_planning"],
                        "additionalProperties": False,
                    },
                    "workday_routine": {
                        "type": "object",
                        "properties": {
                            "power_blocks": {"type": "string"},
                            "team_collaboration": {"type": "string"},
                            "breaks": {"type": "string"},
                        },
                        "required": ["power_blocks", "team_collaboration", "breaks"],
                        "additionalProperties": False,
                    },
                    "evening_routine": {
                        "type": "object",
                        "properties": {
                            "reflection": {"type": "string"},
                            "wind_down": {"type": "string"},
                            "prepare_for_tomorrow": {"type": "string"},
                        },
                        "required": ["reflection", "wind_down", "prepare_for_tomorrow"],
                        "additionalProperties": False,
                    },
                },
                "required": ["morning_routine", "workday_routine", "evening_routine"],
                "additionalProperties": False,
            },
        },
        "required": ["career", "finance", "relationships", "daily_routine"],
        "additionalProperties": False,
    },
    PAYLOAD_CATEGORY.FEAR_AND_MOTIVATION_GENERATOR_DATA: {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "Fears and Motivation Schema",
        "type": "object",
        "properties": {
            "fear_of_not_making_significant_impact": {
                "type": "object",
                "properties": {
                    "mindset_shift": {"type": "string"},
                    "motivation": {"type": "string"},
                    "perspective": {"type": "string"},
                },
                "required": ["mindset_shift", "motivation", "perspective"],
                "additionalProperties": False,
            },
            "fear_of_burnout": {
                "type": "object",
                "properties": {
                    "mindset_shift": {"type": "string"},
                    "motivation": {"type": "string"},
                    "perspective": {"type": "string"},
                },
                "required": ["mindset_shift", "motivation", "perspective"],
                "additionalProperties": False,
            },
            "doubt_about_achieving_financial_freedom": {
                "type": "object",
                "properties": {
                    "mindset_shift": {"type": "string"},
                    "motivation": {"type": "string"},
                    "perspective": {"type": "string"},
                },
                "required": ["mindset_shift", "motivation", "perspective"],
                "additionalProperties": False,
            },
            "doubt_about_successfully_scaling_investment_portfolio": {
                "type": "object",
                "properties": {
                    "mindset_shift": {"type": "string"},
                    "motivation": {"type": "string"},
                    "perspective": {"type": "string"},
                },
                "required": ["mindset_shift", "motivation", "perspective"],
                "additionalProperties": False,
            },
            "final_motivation_to_push_through": {
                "type": "object",
                "properties": {
                    "motivation": {"type": "string"},
                    "remember_your_why": {"type": "string"},
                    "believe_in_your_ability_to_adapt": {"type": "string"},
                },
                "required": [
                    "motivation",
                    "remember_your_why",
                    "believe_in_your_ability_to_adapt",
                ],
                "additionalProperties": False,
            },
        },
        "required": [
            "fear_of_not_making_significant_impact",
            "fear_of_burnout",
            "doubt_about_achieving_financial_freedom",
            "doubt_about_successfully_scaling_investment_portfolio",
            "final_motivation_to_push_through",
        ],
        "additionalProperties": False,
    },
    PAYLOAD_CATEGORY.DAILY_HABIT_GENERATOR_DATA: {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "Daily Success Habits Schema",
        "type": "object",
        "properties": {
            "morning_mindset_ritual": {
                "type": "object",
                "properties": {
                    "why_its_powerful": {"type": "string"},
                    "what_to_do": {"type": "string"},
                    "long_term_impact": {"type": "string"},
                },
                "required": ["why_its_powerful", "what_to_do", "long_term_impact"],
                "additionalProperties": False,
            },
            "focused_learning": {
                "type": "object",
                "properties": {
                    "why_its_powerful": {"type": "string"},
                    "what_to_do": {"type": "string"},
                    "long_term_impact": {"type": "string"},
                },
                "required": ["why_its_powerful", "what_to_do", "long_term_impact"],
                "additionalProperties": False,
            },
            "daily_investment_tracking": {
                "type": "object",
                "properties": {
                    "why_its_powerful": {"type": "string"},
                    "what_to_do": {"type": "string"},
                    "long_term_impact": {"type": "string"},
                },
                "required": ["why_its_powerful", "what_to_do", "long_term_impact"],
                "additionalProperties": False,
            },
            "relationship_building": {
                "type": "object",
                "properties": {
                    "why_its_powerful": {"type": "string"},
                    "what_to_do": {"type": "string"},
                    "long_term_impact": {"type": "string"},
                },
                "required": ["why_its_powerful", "what_to_do", "long_term_impact"],
                "additionalProperties": False,
            },
            "daily_reflection_and_goal_review": {
                "type": "object",
                "properties": {
                    "why_its_powerful": {"type": "string"},
                    "what_to_do": {"type": "string"},
                    "long_term_impact": {"type": "string"},
                },
                "required": ["why_its_powerful", "what_to_do", "long_term_impact"],
                "additionalProperties": False,
            },
            "the_big_picture": {
                "type": "object",
                "properties": {
                    "summary": {"type": "string"},
                    "reminder": {"type": "string"},
                },
                "required": ["summary", "reminder"],
                "additionalProperties": False,
            },
        },
        "required": [
            "morning_mindset_ritual",
            "focused_learning",
            "daily_investment_tracking",
            "relationship_building",
            "daily_reflection_and_goal_review",
            "the_big_picture",
        ],
        "additionalProperties": False,
    },
}
